version: '3.9' # optional since v1.27.0
services:
  relations:
    build: ./relations
    ports:
      - '3000:3000'
    volumes:
      - logvolume01:/var/log
  dateapp:
    command: python3 manage.py runserver
    build: './dateApp'
    ports:
      - '8000:8000'
    volumes:
      - logvolume02:/var/log
    links:
      - relations
      - authentification
  authentification:
    build: ./authentification
    ports:
      - '8080:8080'
    depends_on:
      - flyway
    links:
      - flyway
    volumes:
      - logvolume03:/var/log
  flyway:
    image: dhoer/flyway:alpine
    command: -url=jdbc:mysql://db -schemas=tpalt -user=root -password=ThePassword -connectRetries=60 migrate
    volumes:
      - ./authentification/migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  logvolume01: {}
  logvolume02: {}
  logvolume03: {}
